(() => {
  const start = () => {
    const config = window.WALLVERSE_PUBLIC_CONFIG;
    const dialog = document.getElementById('upload-dialog');
    if (!config || !dialog || !window.supabase?.createClient) return false;
    const client = window.WallverseSupabase || window.supabase.createClient(config.supabaseUrl, config.supabaseAnonKey, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } });
    const fileInput = document.getElementById('upload-file'); const choose = document.getElementById('upload-choose'); const picker = document.getElementById('upload-picker');
    const crop = document.getElementById('upload-crop'); const stage = document.getElementById('upload-crop-stage'); const image = document.getElementById('upload-crop-image'); const zoom = document.getElementById('upload-zoom');
    const fields = document.getElementById('upload-fields'); const status = document.getElementById('upload-status'); const form = document.getElementById('upload-form'); const tagInput = document.getElementById('upload-tag-input'); const tagsNode = document.getElementById('upload-tags');
    const title = document.getElementById('upload-wallpaper-title'); const description = document.getElementById('upload-description'); const category = document.getElementById('upload-category'); const submit = document.getElementById('upload-submit');
    let sourceFile, natural = { width: 0, height: 0 }, scale = 1, position = { x: 0, y: 0 }, drag, tags = [], titleTouched = false, tagsTouched = false, categoryTouched = false;
    const allowedTypes = new Set(['image/jpeg', 'image/png', 'image/webp']);
    const setStatus = (text = '') => { status.textContent = text; };
    const clamp = (value, min, max) => Math.min(max, Math.max(min, value));
    const normalizeTag = (value) => String(value || '').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, '-').replace(/[^a-z0-9_-]/g, '').replace(/-+/g, '-').replace(/^-|-$/g, '');
    const baseScale = () => Math.max(stage.clientWidth / natural.width, stage.clientHeight / natural.height);
    const maxScale = () => Math.max(1, Math.min((stage.clientWidth / 585) / baseScale(), (stage.clientHeight / 1300) / baseScale(), 3));
    const constrain = () => { const renderedW = natural.width * baseScale() * scale, renderedH = natural.height * baseScale() * scale; position.x = clamp(position.x, -(renderedW - stage.clientWidth) / 2, (renderedW - stage.clientWidth) / 2); position.y = clamp(position.y, -(renderedH - stage.clientHeight) / 2, (renderedH - stage.clientHeight) / 2); };
    const drawCrop = () => { constrain(); stage.style.setProperty('--crop-scale', scale); stage.style.setProperty('--crop-x', `${position.x}px`); stage.style.setProperty('--crop-y', `${position.y}px`); zoom.max = String(maxScale()); zoom.value = String(scale); };
    const reset = () => { sourceFile = null; tags = []; title.value = ''; description.value = ''; category.value = 'Anime'; titleTouched = tagsTouched = categoryTouched = false; picker.hidden = false; crop.hidden = true; fields.hidden = true; fileInput.value = ''; setStatus(); renderTags(); };
    const renderTags = () => tagsNode.replaceChildren(...tags.map((tag) => { const node = document.createElement('button'); node.type = 'button'; node.textContent = `${tag} ×`; node.addEventListener('click', () => { tagsTouched = true; tags = tags.filter((value) => value !== tag); renderTags(); }); return node; }));
    const addTag = (raw) => { const tag = normalizeTag(raw); if (!tag) return; if (tag.length < 2 || tag.length > 32) return setStatus('Tags must be 2–32 characters.'); if (['ai-generated', 'ai', 'suggestive', 'nsfw'].includes(tag)) return setStatus('Use the dedicated content toggles instead.'); if (tags.includes(tag)) return; if (tags.length === 15) return setStatus('Use 15 tags maximum.'); tagsTouched = true; tags.push(tag); tagInput.value = ''; setStatus(); renderTags(); };
    const toBlob = (canvas, type, quality) => new Promise((resolve) => canvas.toBlob(resolve, type, quality));
    const blobToBase64 = async (blob) => { const data = await blob.arrayBuffer(); const bytes = new Uint8Array(data); let text = ''; for (let index = 0; index < bytes.length; index += 0x8000) text += String.fromCharCode(...bytes.subarray(index, index + 0x8000)); return btoa(text); };
    const sha256 = async (blob) => [...new Uint8Array(await crypto.subtle.digest('SHA-256', await blob.arrayBuffer()))].map((byte) => byte.toString(16).padStart(2, '0')).join('');
    const output = async (maxWidth = 1260, quality = .85) => {
      const currentBase = baseScale(); const factor = currentBase * scale;
      const sourceW = stage.clientWidth / factor, sourceH = stage.clientHeight / factor;
      const sourceX = natural.width / 2 - sourceW / 2 - position.x / factor, sourceY = natural.height / 2 - sourceH / 2 - position.y / factor;
      const ratio = Math.min(1, maxWidth / sourceW); const width = Math.floor(sourceW * ratio), height = Math.floor(sourceH * ratio);
      const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.getContext('2d').drawImage(image, sourceX, sourceY, sourceW, sourceH, 0, 0, width, height);
      let blob = await toBlob(canvas, 'image/jpeg', quality); if (!blob) throw new Error('Could not encode crop.');
      for (let q = .8; blob.size > 4 * 1024 * 1024 && q >= .55; q -= .1) blob = await toBlob(canvas, 'image/jpeg', q);
      return { blob, width, height, canvas };
    };
    const invoke = async (name, body) => { const { data, error } = await client.functions.invoke(name, { body }); if (error) throw error; if (data?.error) throw new Error(data.error.code || 'Service error'); return data; };
    const suggestMetadata = async () => {
      if (!sourceFile) return; const aiTitle = document.getElementById('upload-ai-title'); const aiCopy = document.getElementById('upload-ai-copy'); const retry = document.getElementById('upload-ai-retry');
      aiTitle.textContent = 'Generating metadata…'; aiCopy.textContent = 'Wallverse AI is suggesting a title, category and tags.'; retry.hidden = true;
      try { const preview = await output(768, .75); const hash = await sha256(sourceFile); let data = await invoke('generate-wallpaper-metadata', { imageHash: hash, lookupOnly: true }); if (data.cacheMiss) data = await invoke('generate-wallpaper-metadata', { imageHash: hash, imageBase64: await blobToBase64(preview.blob), contentType: 'image/jpeg' });
        if (!titleTouched && !title.value.trim() && data.titleSuggestions?.[0]) title.value = data.titleSuggestions[0]; if (!tagsTouched && !tags.length) { tags = (data.tags || []).map(normalizeTag).filter((tag) => tag.length >= 2 && tag.length <= 32).slice(0, 15); renderTags(); } if (!categoryTouched && data.category && [...category.options].some((option) => option.value === data.category)) category.value = data.category; aiTitle.textContent = 'Metadata suggestions ready'; aiCopy.textContent = 'Review the AI suggestions before you submit.';
      } catch (error) { console.warn('Metadata suggestion unavailable.', error); aiTitle.textContent = 'Metadata suggestions unavailable'; aiCopy.textContent = 'You can continue manually.'; retry.hidden = false; }
    };
    const selectFile = async (file) => { if (!file) return; const type = file.type || (file.name.endsWith('.webp') ? 'image/webp' : file.name.match(/\.png$/i) ? 'image/png' : 'image/jpeg'); if (!allowedTypes.has(type)) return setStatus('Choose a JPG, PNG or WebP image.'); const url = URL.createObjectURL(file); image.onload = async () => { URL.revokeObjectURL(url); natural = { width: image.naturalWidth, height: image.naturalHeight }; if (natural.width < 585 || natural.height < 1300) return setStatus('Image is too small. Minimum cropped size is 585 × 1300.'); sourceFile = file; scale = 1; position = { x: 0, y: 0 }; picker.hidden = true; crop.hidden = false; fields.hidden = false; drawCrop(); setStatus('Crop ready. Metadata suggestions are being generated…'); suggestMetadata(); }; image.onerror = () => setStatus('This image could not be read.'); image.src = url; };
    const open = async () => { const { data } = await client.auth.getUser(); if (!data.user) return document.getElementById('auth-trigger')?.click(); if (!dialog.open) dialog.showModal(); };
    const upload = async (event) => { event.preventDefault(); if (!sourceFile) return setStatus('Choose a wallpaper image first.'); const normalized = tags.map(normalizeTag).filter(Boolean); if (title.value.trim().length < 2) return setStatus('Add a title of at least 2 characters.'); if (normalized.length < 3) return setStatus('Add at least 3 tags.'); let hd; try { hd = await output(); if (hd.width < 585 || hd.height < 1300) return setStatus('Crop is too small. Minimum is 585 × 1300.'); if (hd.blob.size > 4 * 1024 * 1024) return setStatus('Crop is too large. Try a simpler image or smaller crop.'); } catch (error) { return setStatus(error.message || 'Could not prepare this image.'); }
      const quality = hd.width >= 1260 && hd.height >= 2800 ? 'premium' : hd.width >= 1080 && hd.height >= 2400 ? 'high' : 'standard'; const thumbCanvas = document.createElement('canvas'); thumbCanvas.width = Math.min(320, hd.width); thumbCanvas.height = Math.round(hd.height * thumbCanvas.width / hd.width); thumbCanvas.getContext('2d').drawImage(hd.canvas, 0, 0, thumbCanvas.width, thumbCanvas.height); let thumb = await toBlob(thumbCanvas, 'image/webp', .8); let thumbType = 'image/webp'; if (!thumb || thumb.size > 1024 * 1024) { thumb = await toBlob(thumbCanvas, 'image/jpeg', .8); thumbType = 'image/jpeg'; } if (!thumb) return setStatus('Could not create thumbnail.'); let wallpaperId = crypto.randomUUID(); submit.disabled = true; dialog.setAttribute('aria-busy', 'true');
      try { setStatus('Preparing HD upload…'); const hdUpload = await invoke('create-r2-upload', { wallpaperId, variant: 'hd', contentType: 'image/jpeg', contentLength: hd.blob.size }); setStatus('Uploading HD file…'); let response = await fetch(hdUpload.uploadUrl, { method: 'PUT', headers: hdUpload.requiredHeaders, body: hd.blob }); if (!response.ok) throw new Error(`Cloudflare rejected the HD upload (${response.status}).`); setStatus('Preparing thumbnail upload…'); const thumbUpload = await invoke('create-r2-upload', { wallpaperId, variant: 'thumbnail', contentType: thumbType, contentLength: thumb.size }); setStatus('Uploading thumbnail…'); response = await fetch(thumbUpload.uploadUrl, { method: 'PUT', headers: thumbUpload.requiredHeaders, body: thumb }); if (!response.ok) throw new Error(`Cloudflare rejected the thumbnail upload (${response.status}).`); setStatus('Verifying Cloudflare files…'); await invoke('finalize-r2-upload', { wallpaperId, title: title.value.trim(), description: description.value.trim(), category: category.value, tags: normalized, width: hd.width, height: hd.height, fileSize: hd.blob.size, quality, isAi: document.getElementById('upload-is-ai').checked, isSuggestive: document.getElementById('upload-is-suggestive').checked }); setStatus('Uploaded and pending review.'); window.setTimeout(() => { dialog.close(); reset(); }, 1400); } catch (error) { console.error('Wallpaper upload failed.', error); if (wallpaperId) invoke('delete-r2-media', { wallpaperId, mode: 'cancel_upload' }).catch(() => {}); setStatus(error.message || 'Upload failed. Please try again.'); } finally { submit.disabled = false; dialog.removeAttribute('aria-busy'); }
    };
    document.querySelectorAll('[data-open-upload]').forEach((button) => button.addEventListener('click', open)); document.querySelector('[data-close-upload]').addEventListener('click', () => dialog.close()); dialog.addEventListener('click', (event) => { if (event.target === dialog) dialog.close(); }); choose.addEventListener('click', () => fileInput.click()); fileInput.addEventListener('change', () => selectFile(fileInput.files?.[0])); zoom.addEventListener('input', () => { scale = Number(zoom.value); drawCrop(); }); document.getElementById('upload-zoom-in').addEventListener('click', () => { scale = clamp(scale + .1, 1, maxScale()); drawCrop(); }); document.getElementById('upload-zoom-out').addEventListener('click', () => { scale = clamp(scale - .1, 1, maxScale()); drawCrop(); }); stage.addEventListener('pointerdown', (event) => { drag = { x: event.clientX, y: event.clientY, px: position.x, py: position.y }; stage.setPointerCapture(event.pointerId); }); stage.addEventListener('pointermove', (event) => { if (!drag) return; position = { x: drag.px + event.clientX - drag.x, y: drag.py + event.clientY - drag.y }; drawCrop(); }); stage.addEventListener('pointerup', () => { drag = null; }); tagInput.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ',') { event.preventDefault(); addTag(tagInput.value); } }); title.addEventListener('input', () => { titleTouched = true; }); category.addEventListener('change', () => { categoryTouched = true; }); document.getElementById('upload-ai-retry').addEventListener('click', suggestMetadata); form.addEventListener('submit', upload); if (new URLSearchParams(window.location.search).get('upload') === '1') window.setTimeout(open, 350); return true;
  };
  if (!start()) window.addEventListener('wallverse:data-ready', start, { once: true });
})();
