(() => {
  const config = window.WALLVERSE_PUBLIC_CONFIG; const helpers = window.WallverseCards;
  if (!config || !helpers || !window.supabase?.createClient) return;
  const client = window.WallverseSupabase || window.supabase.createClient(config.supabaseUrl, config.supabaseAnonKey);
  const uploadTrigger = document.getElementById('creators-upload');
  const renderUploadTrigger = (user) => { if (uploadTrigger) uploadTrigger.hidden = !user; };
  client.auth.getUser().then(({ data }) => renderUploadTrigger(data.user)).catch(() => renderUploadTrigger(null));
  client.auth.onAuthStateChange((_event, session) => renderUploadTrigger(session?.user));
  const ranking = document.getElementById('creators-ranking'); const status = document.getElementById('creators-status');
  let creators = []; let sort = 'power';
  const allPages = async (factory) => { const rows=[]; let offset=0; while(true){ const {data,error}=await factory(offset); if(error) throw error; const page=data||[]; rows.push(...page); if(page.length<1000) return rows; offset+=1000; } };
  const compact = (value) => helpers.compactNumber(value); const createAdCard = helpers.createAdCard; const adCardInterval = helpers.adCardInterval || 12;
  const avatar = (profile) => { const node=document.createElement('span'); const rarity=window.WallverseCardFrames?.creatorRarity(profile,profile)||'common'; node.className='avatar avatar--violet'; node.textContent=(profile.username||'W').charAt(0).toUpperCase(); window.WallverseCardFrames?.applyAvatar(node,profile.avatar_frame_type,rarity); if(profile.avatar_url){const image=new Image(); image.className='avatar__image'; image.alt=''; image.src=profile.avatar_url; image.onload=()=>{node.replaceChildren(image);window.WallverseCardFrames?.applyAvatar(node,profile.avatar_frame_type,rarity);};} return node; };
  const render = () => { const query=document.getElementById('creators-search').value.trim().toLocaleLowerCase(); const filtered=creators.filter((creator)=>!query||String(creator.username||'').toLocaleLowerCase().includes(query)); filtered.sort((a,b)=> (b[sort]||0)-(a[sort]||0) || (b.power||0)-(a.power||0)); const rows=[]; filtered.forEach((creator,index)=>{ const row=document.createElement('button'); row.type='button'; row.className='creator-ranking-row'; row.setAttribute('aria-label',`Open @${creator.username}`); const rank=document.createElement('span'); rank.className='creator-ranking-row__rank'; rank.textContent=String(index+1); const identity=document.createElement('div'); identity.className='creator-ranking-row__identity'; const copy=document.createElement('div'); const name=document.createElement('strong'); name.textContent=`@${creator.username}`; const role=document.createElement('span'); role.textContent=creator.role||'Wallverse creator'; copy.append(name,role); identity.append(avatar(creator),copy); const stats=document.createElement('div'); stats.className='creator-ranking-row__stats'; [['Uploads',creator.uploads],['Cards',creator.cards],['Downloads',creator.downloads],['Followers',creator.followers_count||0],['Power',creator.power]].forEach(([label,value])=>{const item=document.createElement('span');item.innerHTML=`<small>${label}</small><strong>${compact(value)}</strong>`;stats.append(item);}); row.append(rank,identity,stats); row.addEventListener('click',()=>{if(typeof window.WallverseOpenCreator==='function')window.WallverseOpenCreator(creator);else window.dispatchEvent(new CustomEvent('wallverse:creator-inspect',{detail:{profile:creator}}));}); rows.push(row); if((index+1)%adCardInterval===0&&createAdCard)rows.push(createAdCard('wide')); }); ranking.replaceChildren(...rows); status.textContent=filtered.length?`${filtered.length} public creators`:'No creators match this search.'; document.querySelectorAll('[data-creators-sort]').forEach((button)=>{const active=button.dataset.creatorsSort===sort;button.classList.toggle('is-active',active);button.setAttribute('aria-pressed',String(active));}); };
  const load = async () => { try { const [profiles,wallpapers,cards]=await Promise.all([allPages((offset)=>client.from('profiles').select('id,username,role,avatar_url,avatar_frame_type,followers_count').range(offset,offset+999)),allPages((offset)=>client.from('wallpapers').select('user_id,likes_count,downloads_count,views_count,quality,is_featured,is_weekly').eq('status','approved').eq('is_suggestive',false).range(offset,offset+999)),allPages((offset)=>client.from('user_cards').select('owner_id').range(offset,offset+999)).catch(()=>[])]); const byId=new Map(); profiles.forEach((profile)=>byId.set(profile.id,{...profile,uploads:0,cards:0,likes:0,downloads:0,views:0,featured:0,power:0})); wallpapers.forEach((wallpaper)=>{const creator=byId.get(wallpaper.user_id);if(!creator)return;creator.uploads+=1;creator.likes+=Number(wallpaper.likes_count)||0;creator.downloads+=Number(wallpaper.downloads_count)||0;creator.views+=Number(wallpaper.views_count)||0;creator.featured+=wallpaper.is_featured?1:0;creator.power+=helpers.publicCardScore(wallpaper);}); cards.forEach((card)=>{const creator=byId.get(card.owner_id);if(creator){creator.cards+=1;creator.power+=25;}}); creators=[...byId.values()].filter((creator)=>creator.uploads||creator.cards); render(); } catch(error){console.warn('Creator ranking unavailable.',error);status.textContent='Creator ranking is unavailable right now.';} };
  document.getElementById('creators-search').addEventListener('input',render); document.querySelectorAll('[data-creators-sort]').forEach((button)=>button.addEventListener('click',()=>{sort=button.dataset.creatorsSort;render();})); load();
})();
